import { get, update } from "lodash";

export const BASE_URL = import.meta.env.VITE_BASE_URL;
export const BASE_URL_AUTH = import.meta.env.VITE_BASE_URL_AUTH;
export const FLOW_BASE_URL = import.meta.env.VITE_FLOW_BASE_URL;
export const AI_URL = import.meta.env.VITE_AI_URL;
export const Upload_AI_API = import.meta.env.VITE_UPLOAD_AI_API;
export const FORM_BASE_URL = import.meta.env.VITE_FORM_BASE_URL;

export const CLIENT_ID = import.meta.env.VITE_CLIENT_ID;
export const REDIRECT_URI = import.meta.env.VITE_REDIRECT_URI;
export const CLIENT_SECRET = import.meta.env.VITE_CLIENT_SECRET;
export const STATE = import.meta.env.VITE_STATE || "myState";
export const GRAND_TYPE =
  import.meta.env.VITE_GRANT_TYPE || "authorization_code";
export const RESPONSE_TYPE = import.meta.env.VITE_RESPONSE_TYPE || "code";
const version = "v1";
export const ENDPOINT_URL = {
  auth: {
    login: `/api/v1/auth/login`,
    logout: `${version}/iCR2Y/X918ByG1hVUKatj`,
  },
  common: {
    list_process_owner: `${version}/u4wtD/rANUMtWyYkuZ04M`,
    list_end_user: `${version}/u4wtD/rANUMtWyYkuZ05N`,
    list_process_owner_and_end_user: `${version}/u4wtD/wVbRc3blF5fhZxh`,
    generate_token_for_dynamic_form: `${version}/u4wtD/bRc3blFfhZxhwV5`,
    list_user_to_assign_element: `${version}/u4wtD/V5bRcfhZxhw3blF`,
    documentUpload: `${version}/u4wtD/j3PrIxysO5MIZZB`,
    riskDocumentUpload: `${version}/u4wtD/MIBj35ZPsOZrIxy`,
    upload_SOP_PDF: `${version}/u4wtD/vNuRdaH7zqkHQfk`,
    get_element_details: `${version}/P7Y4Y/SjVgWv5DpRc6wwf`,
    trainingSimulationVideoUpload: `${version}/u4wtD/AxMkYtN0k4MUWM`,
    trainingSimulationZipUpload: `${version}/u4wtD/RdaHHQfk7zkvNuq`,
    testSimulationZipUpload: `${version}/u4wtD/fk7zkvNuqRdaHHQ`,
    uploadImage: `${version}/u4wtD/RdaHHQfk7zqkvNu`,
    template_upload_docx: `${version}/u4wtD/aHkHQfkzq7vNuRd`,
    updateEditedDocument: `${version}/1hjr5/basFV5bhZxhwsda`,
  },
  home: {
    dashboard: `${version}/rXos1/K3pG9xL7dR2aM8e`,
    dashboard_actionable: `${version}/rXos1/M8eK3pGdR2a9xL7`,
    leaderboard_toggle_data: `${version}/rXos1/eZaVeybqDvzlRY5`,
    leaderboard_data: `${version}/rXos1/ju9HvL0cgGBE8dl`,
    process_owner_dashboard: `${version}/P7Y4Y/HlpBhKCP3i27AyL`,
    process_owner_actionable: `${version}/P7Y4Y/AyLHlKCP3i27pBh`,
    admin_dashboard: `${version}/P7Y4Y/pbUo3Lzk5HVMf9T`,
    department_overview: `${version}/P7Y4Y/PBvbL4xReDes9Fm`,
    dashboard_element_details: `${version}/P7Y4Y/sUZTpzLXKD0gKhq`,
    dynamic_dashboard: `${version}/rXos1/kYwkXnAwWlPW1vG`,
  },
  training_simulation: {},
  test_simulation: {},
  sops: {},
  attempts: {
    ts_attempts: `${version}/rXos1/X918ByG1hVUKatj`,
  },
  global_search: {
    main_search: `${version}/rXos1/J4dG8xLpM2aR9eK`,
  },
  mcqs: {
    questions_list: `${version}/rXos1/kaw3flV8MyRSkP3`,
    end_test: `${version}/rXos1/evAJI1DhmCsobSd`,
  },
  notification: {
    notification_list: `${version}/P7Y4Y/sn3Ivc4aMlXYaK6`,
    notification_count: `${version}/P7Y4Y/j81IkyzEb37I841`,
    get_count_unread: `${version}/P7Y4Y/rOJ96VCmT8E6kTG`,
  },
  documentone: {
    document_one: `${version}/rXos1/k1sJjoi32FX9YPk`,
  },
  documenttwo: {
    document_two: `${version}/rXos1/k1sJjoi32FX9YPk`,
  },
  sopone: {
    SOP_One: `${version}/rXos1/k1sJjoi32FX9YPk`,
  },
  soptwo: {
    SOP_Two: `${version}/rXos1/k1sJjoi32FX9YPk`,
  },
  elements: {
    left_side_bar: `${version}/rXos1/xDO7as9PXrvJ6Jz`,
    folder_files: `${version}/rXos1/V8bVW2kDsg3jfTq`,
    template_files: `${version}/hI1Ev/XTZPWK4ZL5XAvbQ`,
    document_details: `${version}/rXos1/k1sJjoi32FX9YPk`,
    Category: `${version}/hI1Ev/qxZrQraP39O6qmr`,
    get_chats: `${version}/rXos1/U2A7vgGLDXtAntO`,
    send_message: `${version}/rXos1/spFHbAnUprFi2O1`,
    get_contact_list: `${version}/rXos1/JawZxkqp6VeqHsw`,
    read_chats: `${version}/rXos1/JawZxkqp6VeqHsx`,
    add_comment_to_pdf: `${version}/P7Y4Y/JXWje0yAUK3Iq96`,
    update_comment_to_pdf: `${version}/P7Y4Y/XXreUHDzdtiWbbM`,
    delete_comment_to_pdf: `${version}/P7Y4Y/SWKSNHMqWcU70Ip`,
    reply_resolve_comment_to_pdf: `${version}/P7Y4Y/WN5tCpsv9j6AdOp`,
    add_document_reading_timing: `${version}/rXos1/E6XinuYliInnM2C`,
  },
  rightSideBar: {
    activity_comment: `${version}/rXos1/hUzdVLElM3ATND1`,
    activity_addcomment: `${version}/rXos1/MbmQksU0GCL0Ip8`,
    activity_delegate: `${version}/rXos1/L0IpksU0GC8MbmQ`,
    activity_updated_elegate: `${version}/rXos1/bmQLksU0M0IpGC8`,
    activity_view_history: `${version}/P7Y4Y/k4U5cmnS58I3shg`,
  },
  user: {
    get_user_details: `${version}/rXos1/U6W9W1FZaOrJy6c`,
    update_user_details: `${version}/rXos1/K8pL4eJ9aG7dR2x`,
    change_psw: `${version}/rXos1/RxG3dJ7pL4eM2aK`,
    updateNotifaction: `${version}/rXos1/h7xR3mL9pG2eK8d`,
  },
  favourites: {
    favourites_list: `${version}/rXos1/G7hJ4xR9pL2eM8d`,
    add_favourites_list: `${version}/rXos1/L4xG8dJ7pM2aR5k`,
  },
  documentModule: {
    list_document_draft_version: `${version}/hI1Ev/q5bSSpjTwR2SJaQ`,
    create_document_module: `${version}/hI1Ev/MIZrIxByZj3PsO5`,
    fetch_dox_template: `${version}/hI1Ev/ZPWK4ZLQXT5XAvb`,
    fetch_docx_template_API: `${version}/hI1Ev/ZPWK4ZLQXT5XAvb`,
    bulk_create_document_module: `${version}/hI1Ev/IZrsO5MIxByZj3P`,
    view_document_module_draft: `${version}/hI1Ev/cqMSpln8DrEcx9w`,
    publish_document_module: `${version}/hI1Ev/c8ws3tuvxZuYY8R`,
    delete_document_module: `${version}/hI1Ev/whWe475xubBh21x`,
    export_document_module: `${version}/hI1Ev/xuxwhWeh21475bB`,
    sync_document_module: `${version}/hI1Ev/LPXWAQ5Z4ZXKvbT`,
    update_status_document_module: `${version}/hI1Ev/h21xw75xubBhWe4`,
    create_template: `${version}/hI1Ev/WQZPXTK4ZL5XAvb`,
    published_document_list: `${version}/P7Y4Y/G3YkJciEHSZCNuV`,
    convert_docx_to_pdf: `${version}/hI1Ev/HMTWbvZQALX26gg`,
  },
  trainingSimulationModule: {
    list_training_simulation_draft_version: `${version}/hI1Ev/0QiQx1NM7b1c6FP`,
    create_training_simulation_module: `${version}/hI1Ev/daHHQfkkvNuq7zR`,
    view_training_simulation_module_draft: `${version}/hI1Ev/mwe0jz5IA3U5lVd`,
    publish_training_simulation_module: `${version}/hI1Ev/bxQbbCR2rGOhhUq`,
    delete_training_simulation_module: `${version}/hI1Ev/vCWBWxC05mUQfCr`,
  },
  testSimulationModule: {
    list_test_simulation_draft_version: `${version}/hI1Ev/pXoVGRSeA2lvubb`,
    create_test_simulation_module: `${version}/hI1Ev/xo0uYREJIJe91bR`,
    view_test_simulation_module_draft: `${version}/hI1Ev/bOPB54L4sCQsVz1`,
    publish_test_simulation_module: `${version}/hI1Ev/spB4t1pugF9hnU3`,
    delete_test_simulation_module: `${version}/hI1Ev/yZVbXWwa5Y7SNBO`,
  },
  sopModule: {
    list_sop_draft_version: `${version}/hI1Ev/vA9eTZ75GNq3fJQ`,
    create_sop_module: `${version}/hI1Ev/dedg7DwY10Bpp4h`,
    view_sop_module_draft: `${version}/hI1Ev/dbIc6nabZUgJT4C`,
    publish_sop_module: `${version}/hI1Ev/kDBfR5jCNpgS0zO`,
    delete_sop_module: `${version}/hI1Ev/rDNI5quBqsdDOAD`,
    isTemplate_sop_module_list: `${version}/u4wtD/hZxhw3blFV5bRcf`,
    viewTemplate_sop_module: `${version}/u4wtD/blFV5bhZxhw3Rcf`,
  },
  testMCQModule: {
    create_test_mcq_module: `${version}/hI1Ev/FBKxfNgJOg8w2QW`,
    list_test_mcq_draft_version: `${version}/hI1Ev/j1nCksN95V7zcig`,
    view_test_mcq_module_draft: `${version}/hI1Ev/ojkNUIvYAWw3YZa`,
    publish_test_mcq_module: `${version}/hI1Ev/dDh8IMSEtqNNqSB`,
    delete_test_mcq_module: `${version}/hI1Ev/pLAF1Pk7wV0TRnu`,
    bulk_test_mcqs_upload: `${version}/hI1Ev/2QWFBKxfNOg8wgJ`,
    list_mcqs: `${version}/hI1Ev/egdUxkEKokvoDnE`,
  },
  formModule: {
    create_form_module: `${version}/hI1Ev/PsO5MIZrIxZj3By`,
    list_form_draft_version: `${version}/hI1Ev/2SJaQq5bSwRSpjT`,
    view_form_module_draft: `${version}/hI1Ev/cx9wcqMS8DrEpln`,
    publish_form_module: `${version}/hI1Ev/uYY8Rc8wsvxZ3tu`,
    delete_form_module: `${version}/hI1Ev/xubBhwhWe47521x`,
    verify_user_permission_to_edit_form: `${version}/hI1Ev/hwhW7xubB521xe4`,
  },
  enterprise: {
    get_enterprise_info: `${version}/J2nve/B5uk5l0ie6yq7Fm`,
    add_dipartment: `${version}/P7Y4Y/QmSKW3eWqLJaF0x`,
    getinterprise: `${version}/P7Y4Y/JyBhP2j0jHaxjFz`,
    add_enterprise: `${version}/P7Y4Y/rp6RaU3pdk6O63i`,
    edit_enterprise: `${version}/P7Y4Y/rWJ7QCwCTTrzHjC`,
    delete_enterprise: `${version}/P7Y4Y/f4La2jfINwn15dP`,
    add_role: `${version}/P7Y4Y/xtuSSb5pmLVNyHk`,
    add_zone: `${version}/P7Y4Y/KxQIoWdMUgqx7gU`,
    getroles: `${version}/P7Y4Y/QVIBeIgsiU7G6Ma`,
    update_role: `${version}/P7Y4Y/hdZbxTMwjH9qX2h`,
    get_dep: `${version}/P7Y4Y/xJgYx0Y5JtJIVAD`,
    update_department: `${version}/P7Y4Y/Rjk6bTWPx7S8h9i`,
    update_zone: `${version}/P7Y4Y/rWJ7QCwCTTrzHjC`,
    delete_role: `${version}/P7Y4Y/I1IZjizHgkKE9Dy`,
    delete_zone: `${version}/P7Y4Y/f4La2jfINwn15dP`,
    delete_unit: `${version}/P7Y4Y/f4La2jfINwn15dP`,
    delete_department: `${version}/P7Y4Y/KEIMqCoaliqsnKr`,
    get_zone_api: `${version}/P7Y4Y/ZHkSbYAOE9DE03G`,
    get_unit_api: `${version}/P7Y4Y/q9Sze7ji7GRllDw`,
    pin_elements_api: `${version}/rXos1/rfZmc7KvVgl0GXt`,
  },
  user_management: {
    get_all_users: `${version}/P7Y4Y/fIcc48b3TUbtUAt`,
    delete_user: `${version}/P7Y4Y/p3mXHolwBPjDAVE`,
    update_user: `${version}/P7Y4Y/PpJYxMNV8UzS5tV`,
    search_user: `${version}/P7Y4Y/fIcc48b3TUbtUAt`,
    add_user: `${version}/P7Y4Y/zzNJAjWNWGKRLlh`,
    bluck_user_upload: `${version}/P7Y4Y/u7kSc5FTcE6DtMb`,
  },
  elementAssignment: {
    list_department: `${version}/hI1Ev/w5EaVda512xJ0Hn`,
    list_role: `${version}/hI1Ev/zsMxCrIkhM2hHku`,
    assign_element: `${version}/hI1Ev/sl8vdNH9kj4jAqG`,
    fetch_assigned_data_for_element: `${version}/hI1Ev/u5w7bBhhex2W1x4`,
    revoke_assigned_user_from_element: `${version}/hI1Ev/1x4u5w7hhex2WbB`,
    assing_category: `${version}/P7Y4Y/MZu9rl747NH2eXL`,
  },
  mcq_creations: {
    mcq_list: `${version}/P7Y4Y/skltnHqYdkFERGX`,
    add_mcq: `${version}/P7Y4Y/vB3dZFUDXkBYt37`,
    delete_mcq: `${version}/P7Y4Y/DSr2SPDg57qmFEV`,
    update_mcq: `${version}/P7Y4Y/swfJEf0V3IEbr38`,
  },
  elementDraftActivityLog: {
    view_draft_log: `${version}/hI1Ev/hSdRwo4YCbKiYOx`,
    view_draft_log_history: `${version}/hI1Ev/wohSYOxdRKiCb4Y
 `,
  },
  keygenreration: {
    create: `${version}/P7Y4Y/awdH6VteQbIX7ym`,
  },
  licensekeymanagement: {
    get_license_details: `${version}/P7Y4Y/XRYn3IzR1hvu7e9`,
    add_license_key: `${version}/P7Y4Y/pSmVs02AmRmM6uA`,
  },
  advertisements: {
    get_advertisement: `${version}/P7Y4Y/VqfIBkxXOPYadO1`,
    add_advertisement: `${version}/P7Y4Y/E3eR7lFTRpl6eK7`,
    edit_advertisement: `${version}/P7Y4Y/q8iO4IlHbfFWoso`,
    delete_advertisement: `${version}/P7Y4Y/E4Je5larBsFITlW`,
  },
  reports: {
    user_auth_logs: `${version}/P7Y4Y/CUBvX5Ppu43nEV0`,
    element_publish_logs: `${version}/P7Y4Y/YGYMlauTq7MGYDo`,
    element_access_logs: `${version}/P7Y4Y/tcFBd6kXYsiEKVg`,
    element_process_owner_access_logs: `${version}/P7Y4Y/GQW0MZ4wKyml1Pv`,
    element_activity_transition_logs: `${version}/P7Y4Y/UlLaAVZV6x5A9QL`,
    test_attempt_logs: `${version}/P7Y4Y/SABSde1Uu1JVt39`,
    test_attempt_log_details: `${version}/P7Y4Y/uE6jeQrf6tqmkk4`,
    test_simulation_access_list: `${version}/P7Y4Y/qgwyenLfc6QBjkH`,
    user_list: `${version}/P7Y4Y/fIcc48b3TUbtUAt`,
    module_type_list: `${version}/rXos1/xDO7as9PXrvJ6Jz`,
    element_list: `${version}/P7Y4Y/L5Uu3BLVYIpukNd`,
    unit_list: `${version}/P7Y4Y/dVcIG4U4NcWudwA`,
    department_list: `${version}/P7Y4Y/NvfX5k1iQEvSsf6`,
    role_list: `${version}/P7Y4Y/GvpR1BooKoohGNn`,
    dependent_user_list: `${version}/P7Y4Y/JfjFZqVjgZZXNNP`,
    test_name_list: `${version}/rXos1/eZaVeybqDvzlRY5`,
    get_email_reports: `${version}/hI1Ev/Wex2uhh5w1x47bB`,
    export_campaign: `${version}/hI1Ev/ex2u5w1x47bBWhh`,
    sop_reading_logs: `${version}/P7Y4Y/TGLKb2tPxeqsjxC`,
  },
  impactAnalysis: {
    impact_analysis: `${version}/hI1Ev/iRSYwKhCo4bOdxw`,
  },

  myreq: {
    my_request: `${version}/P7Y4Y/LCyB3EFk9Vu55z3`,
    add_request: `${version}/P7Y4Y/fnvPzQKbPh2VawC`,
    edit_request: `${version}/P7Y4Y/kof11cgOJM1LIu9`,
    delete_request: `${version}/P7Y4Y/edgbV88LNtsTHwi`,
  },
  eSign: {
    upload_esign_pdf: `${version}/rP5GN/0UWMkrZyu4MAYtN`,
    create_esign_request: `${version}/rP5GN/WN0MZ4kutUryMAY`,
    fetch_esign_dashboard_cards: `${version}/rP5GN/MryMAYtUZ4kWN0u`,
    fetch_esign_dashboard: `${version}/rP5GN/ryMAYWN0MutUZ4k`,
    fetch_esign_dashobard_activity: `${version}/rP5GN/0Mu4krZYWNyMAtU`,
    view_esign_request: `${version}/1hjr5/AQZZLPX45XKvbTW`,
    fill_esign_request: `${version}/1hjr5/QZZXvbTWLP45QZZ`,
    bulk_email: `${version}/hI1Ev/47Wex2ubBhh5w1x`,
    get_forms: `${version}/u4wtD/xhwVbRF5fhZc3bl`,
    get_camplist: `${version}/hI1Ev/bBWex2uh1x47h5w`,
  },

  notes: {
    notes_list: `${version}/rXos1/vVlmQ5gQVv6N4ED`,
    add_notes: `${version}/rXos1/GCHJSe90srFmbg8`,
    update_notes: `${version}/rXos1/Xp5TBPPuVf2Urow`,
  },
  Settings: {
    upload_size: `${version}/J2nve/ZmKEWezRqWA5e9B`,
    get_system_settings: `${version}/J2nve/bywT3cLZRVfujK7`,
  },
  SSO: {
    get_sso_link: `${version}/iCR2Y/kleU2PSdOq3EAD1`,
    get_sso_details: `${version}/iCR2Y/z12N7q6OtNL8yTv`,
  },

  RiskandCompliences: {
    add_Risk_Compliences: `${version}/rXos1/HHCSIkyGXtDFGXt`,
    List_Risk_Compliences: `${version}/rXos1/r1jWtjsFxMF14IP`,
  },
  FormSubmission: {
    get_form_submission: `${version}/P7Y4Y/AgDFN3enyPU8OLL`,
  },
  certificate: {
    get_certificate: `${version}/rXos1/MCpHR2eUOOvQLlc`,
  },
  DeleteElements: {
    delete_element: `${version}/rXos1/YZOixmmvP7hzltB`,
  },
  DownloadZIPDocument: {
    download_zip_document: `${version}/P7Y4Y/ZxaYxShD6Ei0yW9`,
  },
  GPT_API: {
    get_gpt: `http://122.166.253.254:5050/api/generate`,
  },
  flow_Digram: {
    addFlow: `${version}/C0IUj/YMDwnk7WaOP8HZk`,
    flowList: `${version}/C0IUj/XOT0V5ZPYlIaCeP`,
    getflowById: `${version}/C0IUj/jnjx5juQ2dMifCx`,
    updateflowPostion: `${version}/C0IUj/vUhrqmonAflKTSF`,
    addservice: `${version}/C0IUj/LGHdL4xQ3gOGQtj`,
    getservicelist: `${version}/C0IUj/uhwOxbD50pTXAxR`,
    getserviceDetails: `${version}/C0IUj/DXPVeS4KTsXIldn`,
    updateFlowDetails: `${version}/C0IUj/d1VoMyumqz9g8T9`,
    addSettings: `${version}/C0IUj/Nn7tHmZhHgCICaW`,
    getSettings: `${version}/C0IUj/H9bG8y9ZsokMn9V`,
    addFlowDetails: `${version}/C0IUj/mC2n5AkGGG06yBD`,
    getflowDetails: `${version}/C0IUj/KkJtsrAefv4YAzO`,
    executeFlow: `${version}/C0IUj/PK7jE3wcL0shkMi`,
    executeStep: `${version}/C0IUj/AEDvXfmfJ9JgFVH`,
    executionRetry: `${version}/C0IUj/BPbhDtKglJ8EFDj`,
    executionHistory: `${version}/C0IUj/qntvbtYmO6JBqLc`,
    updateExecutionHistory: `${version}/C0IUj/TWwIzKLVCTS4BGU`,
    getprevData: `${version}/C0IUj/Es0UlMhnH6ogUcd`,
    getStepDetails: `${version}/C0IUj/DCwunW99pM1wl4l`,
    deleteFlow: `${version}/C0IUj/iRtUeJy9rCTVg4i`,
    getUserList: `${version}/pYaYk/HvacTLXpTk2MpRA`,
    executeFlowHistory: `${version}/C0IUj/n3PQUwhCFa67Vvs`,
    copyWorkFlow: `${version}/C0IUj/yjuCtkml3mgxbqM`,
  },
  elements_folder: {
    hideUnhideModule: `${version}/hI1Ev/hh1x2WbB4u5w7ex`,
  },
  SOP_react_flow: {
    createSOPflow: `${version}/hI1Ev/dgp4hde7DwY10Bp`,
    viweSOPflow: `${version}/hI1Ev/bIcJT4Cd6nabZUg`,
    deleteSOPflow: `${version}/hI1Ev/DNdDOADrI5quBqs`,
    send_sop_upload_pdf_url: `${version}/hI1Ev/vbTAQ5LPXWXKZ4Z`,
  },
  sync_module: {
    syncAllDocuments: `${version}/ubYqd/LPXWAQ5Z4ZXKvbT`,
  },

  group_management: {
    create_group: `${version}/hI1Ev/KZ4ZvQ5WXbTALPX`,
    list_group: `${version}/hI1Ev/ALZvbTAXbTKZ4PX`,
    update_group_single: `${version}/hI1Ev/ZvQ5LPXWXbTAKZ4`,
    delete_group_single: `${version}/hI1Ev/bTKWXZALPX4ZvQ5`,
    add_only_user: `${version}/hI1Ev/PXbTXZWZvQ5AL4K`,
    remove_only_user: `${version}/hI1Ev/LTX4KPXbZWZvQ5A`,
  },
  move_file: {
    move_file_API: `${version}/rXos1/KayGjX91t8B1hVU`,
  },
  SOPRisk: {
    CreateRisk: `${version}/hI1Ev/LQ5ZPX4ZvXZQ5WA`,
    SOP_List: `${version}/hI1Ev/ADdDrI5DNOquBqs`,
    Get_Risk_List: `${version}/hI1Ev/vQALP5bZX4WXZTK`,
    Get_Risk_By_RiskID: `${version}/hI1Ev/P5bvZQALZXTK4WX`,
    Get_RiskAdded_SOPList: `${version}/hI1Ev/AbZXTLvZQP5K4WX`,
    Delete_Risk: `${version}/hI1Ev/XAbTLvZZQ5K4WPX`,
    Edit_Risk: `${version}/hI1Ev/ZQ5PZLQ5X4ZvXWA`,
    Risk_Dashboard: `${version}/hI1Ev/QZXTK5ALZPbv4WX`,
  },
  elementAttributeType: {
    createElementAttributeType: `${version}/I6VF3/Ab9X4zQyWvE1TgR`,
    listElementAttributeType: `${version}/I6VF3/Lm6R8bKtUvY3QnJ`,
    viewElementAttributeType: `${version}/I6VF3/Zp0FcWdNtYo2HvL`,
    deleteElementAttributeType: `${version}/I6VF3/Dj5SaEpBxKw7RmC`,
    linkedElements: `${version}/I6VF3/IMJghjlHxunWeM6`,
  },
  ownerChange: {
    save_owner_change: `${version}/P7Y4Y/TluNqNp8jBcmibZ`,
    auditor_list: `${version}/u4wtD/XqfUekpsJi2a4KO`,
    signatory_list: `${version}/u4wtD/Y5xGBif2YZa6XSf`,
    get_signatory_user_list: `${version}/u4wtD/fpdso51qDHq2k7c`,
    change_signatory: `${version}/u4wtD/E9ZIr3wa5wwcgeC`,
    co_creation_list: `${version}/u4wtD/VEPVbCaUZyhexUE`,
    get_co_creation_user_list: `${version}/u4wtD/b6xaPIRW453B3Yn`,
    save_co_creation: `${version}/u4wtD/E9ZIr3wa5wwcgeC`,
  },
  auditorComment: {
    add_auditor_Comment: `${version}/P7Y4Y/FUSrrQ46EHQib8B`,
  },
  sopattachmentlist: {
    sop_Attachment_List: `${version}/P7Y4Y/BX3WG8wAGTgUCWP`,
  },
  sopTemplate: {
    create_SOP_Template: `${version}/P7Y4Y/IPvvAisydqmOoJZ`,
    list_SOP_Template: `${version}/P7Y4Y/TQo6qHkDNYl6eq0`,
  },
  docTemplate: {
    get_doc_empty_template: `${version}/hI1Ev/bTK4WQLvZZ5XAPX`,
    create_template_and_blank_document: `${version}/hI1Ev/QXAvK4ZLTXZPW5b`,
    Save_and_send: `${version}/hI1Ev/AvKQLZP5TXbX4ZW`,
    delete_template: `${version}/hI1Ev/AL5vZPWbK4ZXXTQ`,
    get_template_list: `${version}/hI1Ev/K4ZXXTZPWAL5vbQ`,
  },
  onlyoffice: {
    office_permission: `${version}/P7Y4Y/gD0EOIgjBdk8As4`,
  },
  dashboard_builder: {
    save_uploaded_dashboard: `${version}/yrL7Y/WBlPL4QhILD1kjJ`,
    get_all_datasource_by_type: `${version}/yrL7Y/x1cYHLn2kawL7EL`,
    get_all_datasource_by_id: `${version}/yrL7Y/nJalS3zwqDQeT5T`,
    update_datasource: `${version}/yrL7Y/V56MAD3ZwoyZ9QR`,
    delete_datasource: `${version}/yrL7Y/MggM8PP342aQIGE`,
    get_all_dashboards: `${version}/yrL7Y/q9xn5ByCIOpY4Gl`,
    create_dynamic_chart: `${version}/yrL7Y/wSo52xloiyTcYgE`,
    get_all_dynamic_chart: `${version}/yrL7Y/ASgEs3MV5wt0wK8`,
    get_dynamic_chart_by_id: `${version}/yrL7Y/b8GqVVfiEE8ByM3`,
    update_dynamic_chart: `${version}/yrL7Y/voDOd8S66Qu5zPA`,
    delete_dynamic_chart: `${version}/yrL7Y/GK15oYHts6f7TY2`,
    assign_chart_to_user: `${version}/yrL7Y/D066ieFs6kTK21U`,
    get_Assigned_Charts_of_current_User: `${version}/yrL7Y/jmfzETYraYXoMYS`,
  },
  email_Template: {
    create_and_edit_mail_template: `${version}/hI1Ev/mkbvZQALZXTK426`,
    get_all_mail_template: `${version}/hI1Ev/ZQALZXTK4Wbv26m`,
    delete_mail_template: `${version}/hI1Ev/TK4WbvZQALX26mk`,
    get_mail_template_by_id: `${version}/hI1Ev/GT4WbvZQALX26m7`,
  },
};
